In [128]:
import numpy as np

In [129]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [130]:
[3.14,4,2.3]

[3.14, 4, 2.3]

In [131]:
np.array([3.14,4,2,3] )

array([3.14, 4.  , 2.  , 3.  ])

In [132]:
np.array([3.14 , 4,3,2] ,dtype = "float32")

array([3.14, 4.  , 3.  , 2.  ], dtype=float32)

In [133]:
a1 = np.array([1,2,3,4])

In [134]:
print(type(a1))

<class 'numpy.ndarray'>


In [135]:
a2 = np.array([[1,2,3],
             [4,5,6]])

In [136]:
print(type(a2))

<class 'numpy.ndarray'>


In [137]:
type(a2)

numpy.ndarray

In [138]:
a2.shape # tinh xem a2 bao nhieeu cot bao nhieeu dong

(2, 3)

In [139]:
a2.ndim # so chieu cua mang

2

In [140]:
a2.dtype

dtype('int32')

In [141]:
a1.dtype

dtype('int32')

In [142]:
a1.size

4

In [143]:
a2.size

6

# creating Numpy Arrays form Scratch
ZERO, ONES , FULL , ARANGE , LINSPACE

In [144]:
# tao mang toan so 0
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [145]:
# tao mang toan so 0
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [146]:
np.ones([2,3] , dtype = float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [147]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [148]:
np.full((3,4),6.9)

array([[6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9]])

In [149]:
np.linspace(0,1,5) # bat dau 0 ket thuc 1 , 5 phan tu co khoang cach bang nhau

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### ham random 

In [150]:
np.random.random((4,4))

array([[0.52889492, 0.56804456, 0.92559664, 0.07103606],
       [0.0871293 , 0.0202184 , 0.83261985, 0.77815675],
       [0.87001215, 0.97861834, 0.79915856, 0.46147936],
       [0.78052918, 0.11827443, 0.63992102, 0.14335329]])

In [151]:
# seed

In [152]:
np.random.seed(0)
np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [153]:
np.random.normal(0,1,(3,3)) # 

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [154]:
# np.random.seed(0)
np.random.randint(0,10,(4,5)) # 4 hang 5 cot ,tu 0->10 nhung ko bao gom 10

array([[7, 2, 0, 0, 4],
       [5, 5, 6, 8, 4],
       [1, 4, 9, 8, 1],
       [1, 7, 9, 9, 3]])

In [155]:
# ngoai ra 
np.random.rand(4,4)

array([[0.65314004, 0.17090959, 0.35815217, 0.75068614],
       [0.60783067, 0.32504723, 0.03842543, 0.63427406],
       [0.95894927, 0.65279032, 0.63505887, 0.99529957],
       [0.58185033, 0.41436859, 0.4746975 , 0.6235101 ]])

# Array Indexing & Slicing

One - dimenstion subarray

In [156]:
import numpy as np
x1 = np.random.randint(10,20, size = 6)
x1 

array([15, 15, 10, 11, 15, 19])

In [157]:
x1[4]

15

In [158]:
x1[0]

15

In [159]:
x1[-1]

19

# multi_dimenstion array

In [160]:
x2 = np.random.randint(0,10 ,(3,4))
x2 

array([[3, 0, 5, 0],
       [1, 2, 4, 2],
       [0, 3, 2, 0]])

In [161]:
x2[1,2] # tính hàng cột bắt đầu từ 0

4

In [162]:
x2[1,2] = 6 # update

In [163]:
x2

array([[3, 0, 5, 0],
       [1, 2, 6, 2],
       [0, 3, 2, 0]])

# slicing

#  x[start: stop : step]

In [164]:
x1

array([15, 15, 10, 11, 15, 19])

In [165]:
x1[0:3] # lấy 3 giá trị đầu tiên

array([15, 15, 10])

In [166]:
x1[4:]

array([15, 19])

In [167]:
# cắt cách nhau 1 step
x1[0:5:2]

array([15, 10, 15])

In [168]:
# cắt toàn bộ mảng cứ cách nhau 2 số là cắt 

In [169]:
x1[::3]

array([15, 11])

In [170]:
x2

array([[3, 0, 5, 0],
       [1, 2, 6, 2],
       [0, 3, 2, 0]])

In [171]:
x2[:2,:3] # 2 hàng ba cột.  lấy hai hàng đầu :2 và ba cột đầu ,:3

array([[3, 0, 5],
       [1, 2, 6]])

In [172]:
x2[:2:] # hai hàng đầu tiên 

array([[3, 0, 5, 0],
       [1, 2, 6, 2]])

In [173]:
x2[:,:2]  # ,: 2 cột đầu tiên

array([[3, 0],
       [1, 2],
       [0, 3]])

# RESHAPING OF ARRAY & TRANSPOSE 

In [174]:
gir = np.arange(1,10)

In [175]:
print(gir)
gir.shape

[1 2 3 4 5 6 7 8 9]


(9,)

In [176]:
gir.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [177]:
x = np.array([1,2,3])

In [178]:
x

array([1, 2, 3])

In [179]:
x.reshape(1,3) # tạo thành 1 ma trận 1*3

array([[1, 2, 3]])

#  Transpose

In [180]:
x = np.array([[1,2,3,4] , [5,6,7,8]])

In [181]:
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [182]:
x.T # chuyển hàng thành cột , cột thành hàng


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

# Array concatenation AND Splitting

In [183]:
# nối 2 aray lại với nhau 
x1 = np.array([1,2,3,4,5])
x2 = np.array([5,6,7,8,9])


In [184]:
np.concatenate((x1,x2)) #nối theo hàng 

array([1, 2, 3, 4, 5, 5, 6, 7, 8, 9])

In [185]:
gird = np.array([[1,2,3]
               ,[4,5,6]])
gird

array([[1, 2, 3],
       [4, 5, 6]])

In [186]:
np.concatenate((gird ,gird))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [187]:
np.concatenate((gird ,gird), axis =1 )

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [188]:
# vstack
x = np.array([[3,2,1]
             ,[8,7,6]])
x

array([[3, 2, 1],
       [8, 7, 6]])

In [189]:
np.vstack((x,gird)) # nối x vói gird

array([[3, 2, 1],
       [8, 7, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [190]:
#horizontally stack
np.hstack((x,gird))

array([[3, 2, 1, 1, 2, 3],
       [8, 7, 6, 4, 5, 6]])

# splitting of array 

In [191]:
x = np.array([2,3,4,5,6,7,8,9,10,11])
np.split(x,[3,5]) # tách ra làm 3 aray khác nhau 

[array([2, 3, 4]), array([5, 6]), array([ 7,  8,  9, 10, 11])]

In [192]:
x1 , x2 ,x3 = np.split(x,[5,7])

In [193]:
x1

array([2, 3, 4, 5, 6])

In [194]:
x2

array([7, 8])

In [195]:
x3

array([ 9, 10, 11])

# Broadcasting AND Vector operations

In [196]:
a = np.arange(3)

In [197]:
a

array([0, 1, 2])

In [198]:
a+5 # broadcasting

array([5, 6, 7])

In [199]:
b = np.ones([3,3] ,dtype = int)

In [200]:
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [201]:
a.shape , b.shape

((3,), (3, 3))

In [202]:
a + b 

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [203]:
a*b

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [204]:
c = np.arange(4).reshape([4,1])

In [205]:
c

array([[0],
       [1],
       [2],
       [3]])

In [206]:
a+c


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

# Manipulating & Comparing Arrays

In [207]:
# aggregation 
list_number = [1,2,3]
ll = np.array(list_number)
ll

array([1, 2, 3])

In [208]:
sum(ll) # python sum

6

In [209]:
np.sum(ll) # python numpy

6

In [210]:
sum(list_number)

6

In [211]:
max_array = np.random.random(10000)

In [212]:
max_array [:5] # lấy 5 phần tử đầu tiên

array([0.60484552, 0.73926358, 0.03918779, 0.28280696, 0.12019656])

In [213]:
max_array.shape

(10000,)

In [214]:
%timeit sum(max_array) # python built_in function
%timeit np.sum(max_array) # Numpy sum

695 µs ± 24.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
6.71 µs ± 134 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [215]:
np.mean(max_array) # hàm trung bình

0.49644077223750666

In [216]:
np.max(max_array) # hàm max 

0.9999779517807228

In [217]:
 np.min(max_array) # hàm min

7.2449638492178e-05

# statistics - Sác Xuất Thống Kê - Độ Lệch Chuẩn - Phương Sai 

In [218]:
import numpy as np


# Standard Deviation And Variance - Độ lệch chuẩn 
 là 1 thước đo , độ phân tán của dữu liệu (so với Min )

In [219]:
dog_height = [600,170,300,470,430]
dog_height = np.array(dog_height)
np.std(dog_height) # độ lệch chuẩn = 600+170 +300 +470 +430 ) /5 = 147.32....

147.32277488562318

# Variance - phương sai 
lấy từng cái dữ liệu 1 trừ cho giá trị trung bình ,sau đó bình phương rồi tính giá trị trung bình đó


In [220]:
np.var(dog_height)  # phương sai 

21704.0

In [221]:
np.sqrt(np.var(dog_height))

147.32277488562318

# shorrting array
squick sorrt

In [222]:
x = np.array([1,45,23,4,3,52,324,453,342,34])

In [223]:
np.sort(x)

array([  1,   3,   4,  23,  34,  45,  52, 324, 342, 453])

In [224]:
 np.argsort(x)  # indexx cua cac phan tu vd : 45 o vitri 1 thi indexx duoi ow vij tri 5 (nghĩa là số 1  bây giờ ở vị trí thứ 5 )

array([0, 4, 3, 2, 9, 1, 5, 6, 8, 7], dtype=int64)

# sorting along row

In [225]:
np.random.seed(42) # 42 nghĩa là nếu seed(42) trên máy tính khác thì nó vẫn như nhau 
mat_a = np.random.randint(0,10,(4,6))

In [226]:
mat_a


array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [227]:
np.sort(mat_a,axis =0) # sắp sếp theo cột axis = 0

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [228]:
np.sort(mat_a,axis =0) # sắp sếp theo hàng axis = 1

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

# LINEAR AIGEBRA

In [229]:
#  HÀM NHÂN MA TRẬN
A = np.array([[1,2,3]
             ,[4,5,6]])
B = np.array([[5,6]
             ,[7,8]
             ,[9,10]])

In [230]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [231]:
B

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [232]:
#  a nhân b = hàng trước nhân cột đứng sau , (c,a) nhân (a,d)
#  công 2 ma trận thì 2 ma trận phải có cùng hàng ngang và hàng dọc

In [233]:
A.dot(B)

array([[ 46,  52],
       [109, 124]])

In [234]:
# hoặc có thể nhân tích vô hướng 
A@B

array([[ 46,  52],
       [109, 124]])

In [235]:
#  vd : (2,3) nhaan ma tran (3,5) = (2,5)
c = np.array([[1,2,3]
             ,[4,5,6]])
D = np.array([[5,6,32,32,32]
             ,[7,8,32,32,3]
             ,[9,10,12,12,12]])

In [236]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [237]:
D


array([[ 5,  6, 32, 32, 32],
       [ 7,  8, 32, 32,  3],
       [ 9, 10, 12, 12, 12]])

In [238]:
c@D

array([[ 46,  52, 132, 132,  74],
       [109, 124, 360, 360, 215]])

In [239]:
#  dot Produc EXample
np.random.seed(0)
sales = np.random.randint(0,20,(5,3))

In [240]:
sales


array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [241]:
import pandas as pd
weekly_sales = pd.DataFrame(sales , index = ["mon" , "Tues" , "Wed","Thus" ,"Fri"] ,
                           columns = ["Almond Butter" , "Peanut Butter", "Cashew Butter"])

In [242]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
mon              12             15              0
Tues              3              3              7
Wed               9             19             18
Thus              4              6             12
Fri               1              6              7

In [243]:
prices = np.array([10,12,15])
butter_price = pd.DataFrame(prices.reshape(1,3) , index = ["Price"] , columns = [" Almond Butter ","Peanut Butter" , "Cashew Butter"])

In [244]:
butter_price

Almond Butter   Peanut Butter  Cashew Butter
Price               10             12             15

In [245]:
weekly_sales.shape ,butter_price.T.shape

((5, 3), (3, 1))

In [246]:
total_price = weekly_sales.dot(butter_price.T)

ValueError: matrices are not aligned

In [ ]:
import numpy as np
s = np.array([[2,3,4] 
            ,[5,6,7]])
y = np.array([[3,4,5]
             ,[54,23,2]])
print(s.shape ,"," ,y.shape) # ko dot() đc do mảng cùng ko có cùng chiều 
print(s.shape ,",",y.T.shape)
s.dot(y.T)

In [ ]:
total_price 

In [126]:
weekly_sales["Total Price"] = total_price
print(weekly_sales)

NameError: name 'total_price' is not defined

In [ ]:

diem = np.array([[2,3,4],[3,5,6]])
ds = pd.DataFrame(diem,index =['0','1' ] , columns=["sang", "tri", "toan"])

In [ ]:
print(ds)